services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: starwars-backend
    ports:
      - "8080:8080"
    networks:
      - starwars-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: starwars-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - starwars-network
    restart: unless-stopped

networks:
  starwars-network:
    driver: bridge